// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPYkoO6jI9_pLXtYvYSPdk_Q1N3CS_C08',
    appId: '1:213853087806:ios:4ee1383ebc1c0e21e1096f',
    messagingSenderId: '213853087806',
    projectId: 'attendance-manager-8bd7d',
    storageBucket: 'attendance-manager-8bd7d.appspot.com',
    iosBundleId: 'com.example.attendanceManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPYkoO6jI9_pLXtYvYSPdk_Q1N3CS_C08',
    appId: '1:213853087806:ios:4ee1383ebc1c0e21e1096f',
    messagingSenderId: '213853087806',
    projectId: 'attendance-manager-8bd7d',
    storageBucket: 'attendance-manager-8bd7d.appspot.com',
    iosBundleId: 'com.example.attendanceManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHHEjsBj1xJVYLJu7KvUCzMYaJlRPLDtU',
    appId: '1:213853087806:web:564520f49224a0dde1096f',
    messagingSenderId: '213853087806',
    projectId: 'attendance-manager-8bd7d',
    authDomain: 'attendance-manager-8bd7d.firebaseapp.com',
    storageBucket: 'attendance-manager-8bd7d.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHHEjsBj1xJVYLJu7KvUCzMYaJlRPLDtU',
    appId: '1:213853087806:web:9d1923536cea4730e1096f',
    messagingSenderId: '213853087806',
    projectId: 'attendance-manager-8bd7d',
    authDomain: 'attendance-manager-8bd7d.firebaseapp.com',
    storageBucket: 'attendance-manager-8bd7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqdgAnFsu4i59v06a0aake8ZC1KVLsIhk',
    appId: '1:213853087806:android:725b8a8f883d9b41e1096f',
    messagingSenderId: '213853087806',
    projectId: 'attendance-manager-8bd7d',
    storageBucket: 'attendance-manager-8bd7d.appspot.com',
  );

}